### ISSUE TITLE
Add Screendoor + Calendly as an "integration"

### ISSUE THREAD

**Issue by kariannemah** [dobtco/wintersmith-knowledge-base#200]
(As discussed in our team call on 5/15)

![screen shot 2015-05-18 at 10 08 56 am](https://cloud.githubusercontent.com/assets/970325/7685814/ececb402-fd45-11e4-801f-addeef44e0dd.png)

It's not an integration per se, but a workflow that can extend the usefulness of Screendoor for hiring or selecting fellows/volunteers. It's for any user who needs to quickly move from applications to phone screens.

(cf. https://github.com/dobtco/dobt/blob/e225696a133bfa33ce33f2d2c8b1279115632a85/design/interviews/2015-01-19-noel-hidalgo.md 
https://github.com/dobtco/dobt/blob/d74717700f004eb6965830ffbf1f70364091cd9a/design/interviews/2015-01-15-rachel-cheetham.md)

**Comment by ajb** [comment]
It would be cool to add this article and then do a blog post about it.

**Comment by kariannemah** [comment]
:+1: I opened an issue in `blog-v2`: https://github.com/dobtco/blog-v2/issues/63.

**Comment by ajb** [comment]
This issue was moved to dobtco/knowledge_base#5
