### ISSUE TITLE
Forms.fm support pages for respondents

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/wintersmith-knowledge-base#223]
- Watching a project
- Creating an account (and why you'd want to)
- Asking a question
- Signing a form
- Editing a response (and asking permission)
- Working on multiple drafts
- Respondent auth
- How to print out your response

These would be nice to have:
- Help pages that match the organization's theme
- Hiding help pages that aren't relevant to a project, to reduce confusion. (i.e. If a project has no questions, don't show the Questions help page.)

**Comment by ajb** [comment]
Marking as `hold` -- it would be nice to find a client that will sponsor this.

**Comment by ajb** [comment]
This issue was moved to dobtco/knowledge_base#4
