### ISSUE TITLE
Add knowledge base images for small screens

### ISSUE THREAD

**Issue by jrubenoff** [dobtco/wintersmith-knowledge-base#226]
Screenshots in the knowledge base are both unreadable on and irrelevant for small screens:

![screen shot 2015-08-24 at 3 03 36 pm](https://cloud.githubusercontent.com/assets/1328849/9453759/5a952af2-4a71-11e5-91e0-c560ab5f8d95.png)

We could use the `picture` element and `srcset` to define more readable images for mobile devices.

**Comment by jrubenoff** [comment]
Oh, and if we want to get fancy (and can produce something that looks nice enough), maybe we could use Phantom.js or something in the future to automate screenshots at different viewports as we update the UI.

**Comment by ajb** [comment]
This issue was moved to dobtco/knowledge_base#7
